# Generated by Django 5.1.1 on 2024-10-09 09:34

import dating.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('age', models.IntegerField(validators=[dating.models.validate_age])),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dating.gender')),
            ],
        ),
    ]
